firstKbRow = document.getElementById("kb-row-one")
console.log("firstKbRow", firstKbRow)

secondKbRow = document.getElementById("kb-row-two")

thirdKbRow = document.getElementById("kb-row-three")

fourthKbRow = document.getElementById("kb-row-four")

fifthKbRow = document.getElementById("kb-row-five")

var key = (function(){
    return{
        makeKey: function(keyText, id){
            keyDiv = document.createElement("div")
            keyDiv.innerText = keyText
            keyDiv.classList.add("key")
            keyDiv.setAttribute("id", id)
            
            return keyDiv
        }
    }
})()

tildeKey = key.makeKey("`", "key-first")
OneKey = key.makeKey("1", "key-one")
TwoKey = key.makeKey("2", "key-two" )
ThreeKey = key.makeKey("3", "key-three")
FourKey = key.makeKey("4", "key-four")
FiveKey = key.makeKey("5", "key-five")
SixKey = key.makeKey("6", "key-six")
SevenKey = key.makeKey("7", "key-seven" )
EightKey = key.makeKey("8" ,"key-eight")
NineKey = key.makeKey("9", "key-nine")
ZeroKey = key.makeKey("0", "key-zero")
DashKey = key.makeKey("-", "key-dash")
EqualKey = key.makeKey("=", "key-equal")
BackspaceKey = key.makeKey("backspace", "key-backspace")

firstKbRow.appendChild(tildeKey)
firstKbRow.appendChild(OneKey)
firstKbRow.appendChild(TwoKey)
firstKbRow.appendChild(ThreeKey)
firstKbRow.appendChild(FourKey)
firstKbRow.appendChild(FiveKey)
firstKbRow.appendChild(SixKey)
firstKbRow.appendChild(SevenKey)
firstKbRow.appendChild(EightKey)
firstKbRow.appendChild(NineKey)
firstKbRow.appendChild(ZeroKey)
firstKbRow.appendChild(DashKey)
firstKbRow.appendChild(EqualKey)
firstKbRow.appendChild(BackspaceKey)

TabKey = key.makeKey("Tab", "key-tab")
QKey = key.makeKey("Q", "key-q")
WKey = key.makeKey("W", "key-w")
EKey = key.makeKey("E", "key-e")
RKey = key.makeKey("R", "key-r")
TKey = key.makeKey("T", "key-t")
YKey = key.makeKey("Y", "key-y")
UKey = key.makeKey("U", "key-u")
IKey = key.makeKey("I", "key-i")
OKey = key.makeKey("O", "key-o")
Pkey = key.makeKey("P", "key-p")
BoxOpenKey = key.makeKey("[", "key-boxopen")
BoxCloseKey = key.makeKey("]", "key-boxclose")
Backslash = key.makeKey("/", "key-backslash")

secondKbRow.appendChild(TabKey)
secondKbRow.appendChild(QKey)
secondKbRow.appendChild(WKey)
secondKbRow.appendChild(EKey)
secondKbRow.appendChild(RKey)
secondKbRow.appendChild(TKey)
secondKbRow.appendChild(YKey)
secondKbRow.appendChild(UKey)
secondKbRow.appendChild(IKey)
secondKbRow.appendChild(OKey)
secondKbRow.appendChild(Pkey)
secondKbRow.appendChild(BoxOpenKey)
secondKbRow.appendChild(BoxCloseKey)
secondKbRow.appendChild(Backslash)

CapsKey = key.makeKey("Caps", "key-caps")
AKey = key.makeKey("A", "key-a")
SKey = key.makeKey("S", "key-s")
DKey = key.makeKey("D", "key-d")
FKey = key.makeKey("F", "key-f")
GKey = key.makeKey("G", "key-g")
HKey = key.makeKey("H", "key-h")
Jkey = key.makeKey("J", "key-j")
KKey = key.makeKey("K", "key-k")
LKey = key.makeKey("L", "key-l")
ComapointKey = key.makeKey(";", "comapoint-key")
HaifinKey = key.makeKey("'", "key-haifin")
EnterKey = key.makeKey("Enter", "key-enter")

thirdKbRow.appendChild(CapsKey)
thirdKbRow.appendChild(AKey)
thirdKbRow.appendChild(SKey)
thirdKbRow.appendChild(DKey)
thirdKbRow.appendChild(FKey)
thirdKbRow.appendChild(GKey)
thirdKbRow.appendChild(HKey)
thirdKbRow.appendChild(Jkey)
thirdKbRow.appendChild(KKey)
thirdKbRow.appendChild(LKey)
thirdKbRow.appendChild(ComapointKey)
thirdKbRow.appendChild(HaifinKey)
thirdKbRow.appendChild(EnterKey)

ShiftKey = key.makeKey("Shift", "key-shift")
ZKey = key.makeKey("Z", "key-z")
XKey = key.makeKey("X", "key-x")
CKey = key.makeKey("C", "key-c")
VKey = key.makeKey("V", "key-v")
BKey = key.makeKey("B", "key-b")
NKey = key.makeKey("N", "key-n")
MKey = key.makeKey("M", "key-m")
LessthanKey = key.makeKey("<", "key-lessthan")
GreaterthanKey = key.makeKey(">", "key-greaterthan")
QuestionmarkKey = key.makeKey("?", "key-questionmark")
ShiftKey2 = key.makeKey("Shift", "key-shift")


fourthKbRow.appendChild(ShiftKey)
fourthKbRow.appendChild(ZKey)
fourthKbRow.appendChild(XKey)
fourthKbRow.appendChild(CKey)
fourthKbRow.appendChild(VKey)
fourthKbRow.appendChild(BKey)
fourthKbRow.appendChild(NKey)
fourthKbRow.appendChild(MKey)
fourthKbRow.appendChild(LessthanKey)
fourthKbRow.appendChild(GreaterthanKey)
fourthKbRow.appendChild(QuestionmarkKey)
fourthKbRow.appendChild(ShiftKey2)

ControlKey = key.makeKey("Ctrl", "key-control")
WindowKey = key.makeKey("Win", "key-windows")
AltKey = key.makeKey("Alt", "key-alt")
SpaceKey = key.makeKey("Space", "key-space")
AltKey2 = key.makeKey("Alt", "key-alt")
WindowKey2 = key.makeKey("Win", "key-windows")
ControlKey2 = key.makeKey("Ctrl", "key-control")

fifthKbRow.appendChild(ControlKey)
fifthKbRow.appendChild(WindowKey)
fifthKbRow.appendChild(AltKey)
fifthKbRow.appendChild(SpaceKey)
fifthKbRow.appendChild(AltKey2)
fifthKbRow.appendChild(WindowKey2)
fifthKbRow.appendChild(ControlKey2)